# -*- coding: utf-8 -*-
"""churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dACsJU6UmxaWu6jIupXAj1bld1TTQl6v
"""

pip install faker

from faker import Faker

fake = Faker()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = []

for i in range(100000):
    age = np.random.randint(18, 71)
    gender = np.random.choice(["Male", "Female"])
    tenure = np.random.randint(0, 11)
    balance = round(np.random.uniform(0, 200000), 2)
    credit_score = np.random.randint(300, 901)
    salary = round(np.random.uniform(10000, 150000), 2)
    products = np.random.randint(1, 5)
    active = np.random.choice(["Yes", "No"])
    churn = 1 if (balance < 50000 and active == "No") else 0

    data.append([
        i+1, age, gender, tenure, balance,
        credit_score, salary, products, active, churn
    ])

df = pd.DataFrame(data, columns=[
    "Customer_ID", "Age", "Gender", "Tenure", "Balance",
    "CreditScore", "EstimatedSalary", "NumOfProducts",
    "IsActiveMember", "Churn"
])

df.head()

print(df.isnull().sum())
df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})
df["IsActiveMember"] = df["IsActiveMember"].map({"Yes": 1, "No": 0})

df.info()

print(df.describe())
print("Mean:\n", df.mean())
print("Median:\n", df.median())
print("Standard Deviation:\n", df.std())

print(df["Churn"].value_counts())
print(df["Churn"].value_counts(normalize=True) * 100)

print(pd.crosstab(df["Gender"], df["Churn"]))
print(pd.crosstab(df["IsActiveMember"], df["Churn"]))
print(pd.crosstab(df["NumOfProducts"], df["Churn"]))

corr = df.corr()
print(corr)

"""BAR CHART"""

sns.countplot(x="Churn", data=df)
plt.title("Churn Distribution")
plt.xlabel("Churn (0 = No, 1 = Yes)")
plt.ylabel("Number of Customers")
for p in plt.gca().patches:
    plt.gca().annotate(p.get_height(),
                       (p.get_x()+0.3, p.get_height()+100))

plt.show()

"""PIE CHART"""

df["Churn"].value_counts().plot.pie(
    autopct="%1.1f%%",
    labels=["No Churn", "Churn"],
    startangle=90
)
plt.title("Churn Percentage")
plt.ylabel("")
plt.show()

"""HISTOGRAM"""

plt.hist(df["Age"], bins=30)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

"""SCATTER PLOT"""

sample_df = df.sample(1000)
plt.scatter(sample_df["Balance"], sample_df["EstimatedSalary"])
plt.title("Balance vs Salary")
plt.xlabel("Balance")
plt.ylabel("Salary")
plt.show()

"""BOX PLOT"""

sns.boxplot(x="Churn", y="Balance", data=df)
plt.title("Balance vs Churn")
plt.xlabel("Churn")
plt.ylabel("Balance")
plt.show()

"""HEAT MAP"""

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

print("Average Balance (Churned):", df[df["Churn"]==1]["Balance"].mean())
print("Average Balance (Not Churned):", df[df["Churn"]==0]["Balance"].mean())
print("Inactive Members Churn Rate:")
print(df[df["IsActiveMember"]==0]["Churn"].mean())